In [1]:
import numpy as np

In [2]:
arr=np.random.randn(1,10,5)

In [3]:
arr

array([[[ 0.94762961,  0.97882852, -0.2590033 , -0.13885055,
         -0.22606818],
        [-0.47210044, -0.20300658,  0.03749874, -0.097932  ,
         -0.02448062],
        [ 0.42902161,  2.26160027, -2.12588537,  0.80253412,
         -1.12257415],
        [ 0.13586391,  0.33147886,  1.27955394,  0.3726963 ,
          0.99472252],
        [-0.38292988,  1.01253476, -1.02456702,  0.5451175 ,
          0.3861864 ],
        [-1.92218707, -1.41768122,  1.12112939,  0.14179467,
          1.09702254],
        [-0.82234936, -0.68024233,  0.31541319, -1.47071452,
          1.41301009],
        [-0.42042844,  1.25933054, -3.23576287,  2.363052  ,
          0.20468893],
        [-0.38768946,  0.46902515, -0.73384396,  0.53862371,
         -0.86955265],
        [-0.2358831 , -1.51956287,  0.59923441, -0.13311296,
         -0.58426094]]])

In [7]:
a=[[1,2,3],
  [4,5,6]]


b=[[1,2,3],
  [4,5,6]]

In [8]:
a

[[1, 2, 3], [4, 5, 6]]

In [9]:
b

[[1, 2, 3], [4, 5, 6]]

In [10]:
a=np.array(a)

In [11]:
b=np.array(b)

In [12]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a*b

array([[ 1,  4,  9],
       [16, 25, 36]])

In [16]:
c=[[4,5,6],
  [7,8,9]]

In [17]:
c=np.array(c)

In [18]:
c

array([[4, 5, 6],
       [7, 8, 9]])

In [19]:
a*b*c

array([[  4,  20,  54],
       [112, 200, 324]])

In [20]:
c @ a

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [24]:
d=[[1,2,3],
  [4,5,6],
  [7,8,9]]

e=[[1,2,3],
  [4,5,6],
  [7,8,9]]

In [27]:
d=np.array(d)
e=np.array(e)

In [28]:
d@e

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [30]:
lin=np.linspace(1,50,100)

In [31]:
lin

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [32]:
np.pi

3.141592653589793

In [39]:
x=[np.pi*var for var in range(1,50)]

In [40]:
x

[3.141592653589793,
 6.283185307179586,
 9.42477796076938,
 12.566370614359172,
 15.707963267948966,
 18.84955592153876,
 21.991148575128552,
 25.132741228718345,
 28.274333882308138,
 31.41592653589793,
 34.55751918948772,
 37.69911184307752,
 40.840704496667314,
 43.982297150257104,
 47.12388980384689,
 50.26548245743669,
 53.40707511102649,
 56.548667764616276,
 59.690260418206066,
 62.83185307179586,
 65.97344572538566,
 69.11503837897544,
 72.25663103256524,
 75.39822368615503,
 78.53981633974483,
 81.68140899333463,
 84.82300164692441,
 87.96459430051421,
 91.106186954104,
 94.24777960769379,
 97.38937226128358,
 100.53096491487338,
 103.67255756846318,
 106.81415022205297,
 109.95574287564276,
 113.09733552923255,
 116.23892818282235,
 119.38052083641213,
 122.52211349000193,
 125.66370614359172,
 128.8052987971815,
 131.94689145077132,
 135.0884841043611,
 138.23007675795088,
 141.3716694115407,
 144.51326206513048,
 147.6548547187203,
 150.79644737231007,
 153.93804002589985]

In [47]:
ara=np.arange(1,50)

In [48]:
ara

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [51]:
ara.reshape((7,7))

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [55]:
len(x)

49

In [57]:
x.reshape(7,7)

AttributeError: 'list' object has no attribute 'reshape'

In [58]:
x=np.array(x)

In [60]:
x.reshape(7,7)

array([[  3.14159265,   6.28318531,   9.42477796,  12.56637061,
         15.70796327,  18.84955592,  21.99114858],
       [ 25.13274123,  28.27433388,  31.41592654,  34.55751919,
         37.69911184,  40.8407045 ,  43.98229715],
       [ 47.1238898 ,  50.26548246,  53.40707511,  56.54866776,
         59.69026042,  62.83185307,  65.97344573],
       [ 69.11503838,  72.25663103,  75.39822369,  78.53981634,
         81.68140899,  84.82300165,  87.9645943 ],
       [ 91.10618695,  94.24777961,  97.38937226, 100.53096491,
        103.67255757, 106.81415022, 109.95574288],
       [113.09733553, 116.23892818, 119.38052084, 122.52211349,
        125.66370614, 128.8052988 , 131.94689145],
       [135.0884841 , 138.23007676, 141.37166941, 144.51326207,
        147.65485472, 150.79644737, 153.93804003]])

In [61]:
import matplotlib.pyplot as plt
%matplotlib inline